# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=znver2 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
MAKEOPTS="-j14 -l8"

USE="-gnome -kde gtk -dvd -cdr -systemd -av1 -ipv6 -telemetry -plasma -fortran -debug -test -lxde \
-lxqt -perl -ruby -serial -nouveau -ldap -kerberos -v4l -dvb -apm\
alsa qt5 qt6 wayland Xwayland X pipewire openrc vulkan opencl dbus udisks flatpak ffmpeg vaapi \
vdpau hevc wifi polkit rar zip pam ssl gamepad networkmanager nfs samba unicode xattr acl elogin acpi"

VIDEO_CARDS="amdgpu radeonsi nvidia"

GRUB_PLATFORMS="efi-64"

ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="* -@EULA unRAR"
